# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-05 07:29
from __future__ import unicode_literals

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AppUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cash', models.FloatField(validators=[django.core.validators.MinValueValidator(0.0)])),
                ('bank_account_number', models.CharField(max_length=64)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Bet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bet_amount', models.FloatField(validators=[django.core.validators.MinValueValidator(0.01)])),
                ('bet', models.IntegerField(choices=[(1, 1), (2, 2), (3, 3)])),
                ('bet_course', models.FloatField(default=0)),
                ('bet_result', models.IntegerField(blank=True, default=0)),
                ('bet_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bet_user', to='betapp.AppUser')),
            ],
        ),
        migrations.CreateModel(
            name='Competition',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('caption', models.CharField(max_length=128)),
                ('league', models.CharField(max_length=12)),
                ('number_of_matchdays', models.IntegerField()),
                ('year', models.IntegerField()),
                ('number_of_teams', models.IntegerField()),
                ('current_matchday', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Fixture',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.IntegerField(choices=[(1, 'SCHEDULED'), (2, 'FINISHED')], default=1)),
                ('matchday', models.IntegerField()),
                ('date', models.DateTimeField()),
                ('goals_home_team', models.IntegerField(blank=True, default=None, null=True)),
                ('goals_away_team', models.IntegerField(blank=True, default=None, null=True)),
                ('course_team_home_win', models.FloatField(blank=True, default=1)),
                ('course_team_away_win', models.FloatField(blank=True, default=1)),
                ('course_draw', models.FloatField(blank=True, default=1)),
                ('fixture_result', models.IntegerField(blank=True, default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('crest_url', models.CharField(blank=True, max_length=256, null=True)),
                ('squad_market_value', models.CharField(blank=True, max_length=64, null=True)),
                ('code', models.CharField(max_length=12, null=True)),
                ('short_name', models.CharField(max_length=64)),
                ('competition', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='betapp.Competition')),
            ],
        ),
        migrations.AddField(
            model_name='fixture',
            name='away_team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='awayTeam', to='betapp.Team'),
        ),
        migrations.AddField(
            model_name='fixture',
            name='competition',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='competition', to='betapp.Competition'),
        ),
        migrations.AddField(
            model_name='fixture',
            name='home_team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='homeTeam', to='betapp.Team'),
        ),
        migrations.AddField(
            model_name='bet',
            name='fixture',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fixture', to='betapp.Fixture'),
        ),
    ]
