# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-04 08:04
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Competition',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('caption', models.CharField(max_length=128)),
                ('league', models.CharField(max_length=12)),
                ('numberOfMatchdays', models.IntegerField()),
                ('year', models.IntegerField()),
                ('numberOfTeams', models.IntegerField()),
                ('currentMatchday', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Fixture',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=64)),
                ('matchday', models.IntegerField()),
                ('date', models.DateTimeField()),
                ('goalsHomeTeam', models.IntegerField(default=None, null=True)),
                ('goalsAwayTeam', models.IntegerField(default=None, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('crestUrl', models.CharField(max_length=256, null=True)),
                ('squadMarketValue', models.CharField(max_length=64, null=True)),
                ('code', models.CharField(max_length=12, null=True)),
                ('shortName', models.CharField(max_length=64)),
            ],
        ),
        migrations.AddField(
            model_name='fixture',
            name='awayTeam',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='awayTeam', to='betapp.Team'),
        ),
        migrations.AddField(
            model_name='fixture',
            name='competition',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='competition', to='betapp.Competition'),
        ),
        migrations.AddField(
            model_name='fixture',
            name='homeTeam',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='homeTeam', to='betapp.Team'),
        ),
    ]
