# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-06 12:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('betapp', '0002_auto_20170705_0845'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fixture',
            name='status',
            field=models.IntegerField(choices=[(1, 'SCHEDULED'), (2, 'FINISHED'), (3, 'PLAYING')], default=1),
        ),
    ]
