# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-04 08:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('betapp', '0002_team_competition'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='crestUrl',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='team',
            name='squadMarketValue',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
    ]
