# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-04 08:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('betapp', '0003_auto_20170704_0813'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fixture',
            name='status',
            field=models.IntegerField(choices=[(1, 'SCHEDULED'), (2, 'PLAYED')]),
        ),
    ]
