# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-07 10:39
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('betapp', '0004_auto_20170706_1356'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appuser',
            name='cash',
            field=models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(0.0)]),
        ),
        migrations.AlterField(
            model_name='bet',
            name='bet_result',
            field=models.IntegerField(blank=True, choices=[(0, 'LOST'), (1, 'WON'), (2, 'PENDING')], default=2),
        ),
    ]
