# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-04 08:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('betapp', '0004_auto_20170704_0817'),
    ]

    operations = [
        migrations.AddField(
            model_name='fixture',
            name='course_draw',
            field=models.FloatField(blank=True, default=1),
        ),
        migrations.AddField(
            model_name='fixture',
            name='course_team_away_win',
            field=models.FloatField(blank=True, default=1),
        ),
        migrations.AddField(
            model_name='fixture',
            name='course_team_home_win',
            field=models.FloatField(blank=True, default=1),
        ),
        migrations.AlterField(
            model_name='fixture',
            name='goalsAwayTeam',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='fixture',
            name='goalsHomeTeam',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
    ]
