# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-10 14:07
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('betapp', '0006_auto_20170707_1043'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appuser',
            name='cash',
            field=models.DecimalField(decimal_places=2, max_digits=6, validators=[django.core.validators.MinValueValidator(0.0)]),
        ),
        migrations.AlterField(
            model_name='bet',
            name='bet_amount',
            field=models.DecimalField(decimal_places=2, max_digits=6, validators=[django.core.validators.MinValueValidator(0.01)]),
        ),
    ]
