# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-04 10:44
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('betapp', '0008_appuser'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bet_amount', models.FloatField(validators=[django.core.validators.MinValueValidator(0.01)])),
                ('bet', models.IntegerField(choices=[(1, 1), (2, 2), (3, 3)])),
                ('bet_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bet_user', to='betapp.AppUser')),
            ],
        ),
        migrations.AddField(
            model_name='fixture',
            name='fixture_result',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='bet',
            name='fixture',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fixture', to='betapp.Fixture'),
        ),
    ]
