# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-04 10:48
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('betapp', '0009_auto_20170704_1044'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bet',
            name='bet_user',
        ),
        migrations.RemoveField(
            model_name='bet',
            name='fixture',
        ),
        migrations.DeleteModel(
            name='Bet',
        ),
    ]
