# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-04 10:48
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('betapp', '0010_auto_20170704_1048'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bet_amount', models.FloatField(validators=[django.core.validators.MinValueValidator(0.01)])),
                ('bet', models.IntegerField(choices=[(1, 1), (2, 2), (3, 3)])),
                ('bet_result', models.IntegerField()),
                ('bet_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bet_user', to='betapp.AppUser')),
                ('fixture', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fixture', to='betapp.Fixture')),
            ],
        ),
    ]
