# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-04 13:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('betapp', '0011_bet'),
    ]

    operations = [
        migrations.AddField(
            model_name='bet',
            name='bet_course',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='bet',
            name='bet_result',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
